import type { NextPage } from "next"
import { signIn } from "next-auth/react"
import Head from "next/head"
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <section className="dark:bg-dark-background-secondary bg-light-background p-4 rounded-md flex flex-col space-y-4 shadow-lg">
          <h1 className="text-2xl font-bold text-center">
            Allen Expense Tracker
          </h1>

          <button
            onClick={async () =>
              signIn("discord", {
                callbackUrl: "/dashboard",
              })
            }
            className="py-2 px-4 bg-purple-500 hover:bg-purple-600 focus:ring-4 outline-none ring-purple-200 text-white rounded-md font-semibold"
          >
            Login with Discord
          </button>
        </section>
      </main>
    </>
  )
}

export default Home
